// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.23.1
// source: test.proto

package testpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Center_OnCall_FullMethodName = "/testpb.Center/OnCall"
)

// CenterClient is the client API for Center service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CenterClient interface {
	OnCall(ctx context.Context, in *OnCallReq, opts ...grpc.CallOption) (*OnCallReply, error)
}

type centerClient struct {
	cc grpc.ClientConnInterface
}

func NewCenterClient(cc grpc.ClientConnInterface) CenterClient {
	return &centerClient{cc}
}

func (c *centerClient) OnCall(ctx context.Context, in *OnCallReq, opts ...grpc.CallOption) (*OnCallReply, error) {
	out := new(OnCallReply)
	err := c.cc.Invoke(ctx, Center_OnCall_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CenterServer is the server API for Center service.
// All implementations must embed UnimplementedCenterServer
// for forward compatibility
type CenterServer interface {
	OnCall(context.Context, *OnCallReq) (*OnCallReply, error)
	mustEmbedUnimplementedCenterServer()
}

// UnimplementedCenterServer must be embedded to have forward compatible implementations.
type UnimplementedCenterServer struct {
}

func (UnimplementedCenterServer) OnCall(context.Context, *OnCallReq) (*OnCallReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnCall not implemented")
}
func (UnimplementedCenterServer) mustEmbedUnimplementedCenterServer() {}

// UnsafeCenterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CenterServer will
// result in compilation errors.
type UnsafeCenterServer interface {
	mustEmbedUnimplementedCenterServer()
}

func RegisterCenterServer(s grpc.ServiceRegistrar, srv CenterServer) {
	s.RegisterService(&Center_ServiceDesc, srv)
}

func _Center_OnCall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OnCallReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CenterServer).OnCall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Center_OnCall_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CenterServer).OnCall(ctx, req.(*OnCallReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Center_ServiceDesc is the grpc.ServiceDesc for Center service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Center_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "testpb.Center",
	HandlerType: (*CenterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OnCall",
			Handler:    _Center_OnCall_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "test.proto",
}

const (
	Agent_OnCall_FullMethodName = "/testpb.Agent/OnCall"
)

// AgentClient is the client API for Agent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentClient interface {
	OnCall(ctx context.Context, in *OnCallReq, opts ...grpc.CallOption) (*OnCallReply, error)
}

type agentClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentClient(cc grpc.ClientConnInterface) AgentClient {
	return &agentClient{cc}
}

func (c *agentClient) OnCall(ctx context.Context, in *OnCallReq, opts ...grpc.CallOption) (*OnCallReply, error) {
	out := new(OnCallReply)
	err := c.cc.Invoke(ctx, Agent_OnCall_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServer is the server API for Agent service.
// All implementations must embed UnimplementedAgentServer
// for forward compatibility
type AgentServer interface {
	OnCall(context.Context, *OnCallReq) (*OnCallReply, error)
	mustEmbedUnimplementedAgentServer()
}

// UnimplementedAgentServer must be embedded to have forward compatible implementations.
type UnimplementedAgentServer struct {
}

func (UnimplementedAgentServer) OnCall(context.Context, *OnCallReq) (*OnCallReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnCall not implemented")
}
func (UnimplementedAgentServer) mustEmbedUnimplementedAgentServer() {}

// UnsafeAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServer will
// result in compilation errors.
type UnsafeAgentServer interface {
	mustEmbedUnimplementedAgentServer()
}

func RegisterAgentServer(s grpc.ServiceRegistrar, srv AgentServer) {
	s.RegisterService(&Agent_ServiceDesc, srv)
}

func _Agent_OnCall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OnCallReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).OnCall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_OnCall_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).OnCall(ctx, req.(*OnCallReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Agent_ServiceDesc is the grpc.ServiceDesc for Agent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Agent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "testpb.Agent",
	HandlerType: (*AgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OnCall",
			Handler:    _Agent_OnCall_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "test.proto",
}
